### ISSUE TITLE
Cannot read property 'operation' of null and could not connect to websocket 

### ISSUE THREAD

**Issue by minhazfm** [michalkvasnicak/aws-lambda-graphql#111]
First I just want to say thank you @michalkvasnicak for this library! Finding this library hopefully saves me time building out a new service I'm trying to implement.

I am trying to test this library locally using `serverless-offline`, and believe I have followed all requirements, but keep getting the following error when I subscribe to my subscription:

```
TypeError: Cannot read property 'operation' of null
    at Object.execute (/Users/Projects/project-graphql/node_modules/aws-lambda-graphql/src/execute.ts:182:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /Users/Projects/project-graphql/node_modules/aws-lambda-graphql/src/Server.ts:539:28
    at InProcessRunner.run (/Users/Projects/project-graphql/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:121:24)
    at LambdaFunction.runHandler (/Users/Projects/project-graphql/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:321:20)
    at WebSocketClients._processEvent (/Users/Projects/project-graphql/node_modules/serverless-offline/dist/events/websocket/WebSocketClients.js:114:7)
```

and then another error when I try to send a mutation for the subscription:

```
{
  "error": "Could not connect to websocket endpoint ws://localhost:3001. Please check if the endpoint url is correct."
}
```

Here is my code:

// Class to construct all `aws-lambda-graphql` methods
```
export class DynamoDBService {
  private connectionManagerInstance: DynamoDBConnectionManager;
  private static instance: DynamoDBService;
  private pubSubInstance: PubSub;
  private subscriptionManagerInstance: DynamoDBSubscriptionManager;

  private constructor() {
    // serverless offline support
    const dynamoDbClient = new DynamoDB.DocumentClient({
      // use serverless-dynamodb endpoint in offline mode
      ...(process.env.IS_OFFLINE
        ? {
            endpoint: "http://localhost:8000",
          }
        : {}),
    });
    const eventStore = new DynamoDBEventStore({
      dynamoDbClient,
      eventsTable: CONSTANTS.DYNAMODB_EVENTS_TABLE,
    });
    this.pubSubInstance = new PubSub({ eventStore });

    this.subscriptionManagerInstance = new DynamoDBSubscriptionManager({
      dynamoDbClient,
      subscriptionOperationsTableName:
        CONSTANTS.DYNAMODB_SUBSCRIPTION_OPERATIONS_TABLE,
      subscriptionsTableName: CONSTANTS.DYNAMODB_SUBSCRIPTIONS_TABLE,
    });

    this.connectionManagerInstance = new DynamoDBConnectionManager({
      // this one is weird but we don't care because you'll use it only if you want to use serverless-offline
      // why is it like that? because we are extracting api gateway endpoint from received events
      // but serverless offline has wrong stage and domainName values in event provided to websocket handler
      // so we need to override the endpoint manually
      // please do not use it otherwise because we need correct endpoint, if you use it similarly as dynamoDBClient above
      // you'll end up with errors
      apiGatewayManager: process.env.IS_OFFLINE
        ? new ApiGatewayManagementApi({
            endpoint: "http://localhost:3001",
          })
        : undefined,
      connectionsTable: CONSTANTS.DYNAMODB_CONNECTIONS_TABLE,
      dynamoDbClient,
      subscriptions: this.subscriptionManagerInstance,
    });

    console.log(`Initiated DynamoDB`);
  }

  static getInstance(): DynamoDBService {
    if (!DynamoDBService.instance) {
      DynamoDBService.instance = new DynamoDBService();
    }

    return DynamoDBService.instance;
  }

  get connectionManager() {
    return this.connectionManagerInstance;
  }

  get pubSub() {
    return this.pubSubInstance;
  }

  get subscriptionManager() {
    return this.subscriptionManagerInstance;
  }
}

export const dynamoDbService = DynamoDBService.getInstance();
```

// Server implementation
```
  private generateServer(): Server {
    const dDBService = dynamoDbService;

    const otherResolvers = {
      Mutation: {
        stripeMessage: async (
          _parent: any,
          args: MessageRequest,
          _context: ResolverContext
        ) => {
          try {
            // const { message } = args;
            await dynamoDbService.pubSub.publish("NEW_MESSAGE", args);

            return {
              success: true,
            };
          } catch (error) {
            throw error;
          }
        },
      },
      Subscription: {
        stripeFeed: {
          resolve: (value: MessageRequest) => value,
          subscribe: dDBService.pubSub.subscribe("NEW_MESSAGE"),
        },
      },
    };

    return new Server({
      connectionManager: dDBService.connectionManager,
      eventProcessor: new DynamoDBEventProcessor(),
      debug: CONSTANTS.IS_OFFLINE,
      typeDefs: typeDefs,
      resolvers: merge(resolvers, otherResolvers),
      subscriptionManager: dDBService.subscriptionManager,
      // Only for local development
      ...(process.env.IS_OFFLINE
        ? {
            playground: {
              endpoint: "/dev/playground",
              subscriptionEndpoint: "ws://localhost:3001",
            },
          }
        : {}),
      formatError: (error) => {
        return ErrorBuilder.generalError(error);
      },
      introspection: true,
      context: async ({
        event,
        context,
      }: {
        event: ApiEvent | ApiWebSocketEvent;
        context: ApiContext;
      }) => {
        try {
          const userId: string | undefined =
            event.requestContext.authorizer?.principalId;

          if (event.path === "/graphql/auth" && !userId) {
            throw new AuthenticationError(
              "Must be signed in to access this resource"
            );
          }

          await connectToDatabase();

          const result: ResolverContext = {
            headers: event.headers,
            event,
            context,
            services: {
              cognitoService: this.cognitoService,
              paymentsService: this.paymentsService,
            },
            sourceIp: event.requestContext.identity.sourceIp,
            userId: userId,
          };
          return result;
        } catch (error) {
          throw error;
        }
      },
    });
  }
```

// Handlers
```
export const graphQLHandler: ApiHandler = (
  event: ApiEvent,
  context: ApiContext,
  callback: ApiCallback
) => {
  context.callbackWaitsForEmptyEventLoop = false;

  try {
    const gQLHandler = apolloService.graphQLServer.createHandler({
      cors: {
        origin: "*",
        credentials: true,
      },
    });
    return gQLHandler(event, context, callback);
  } catch (error) {
    return ApiResponseBuilder.failure(error, callback);
  }
};

export const streamEventHandler = apolloService.graphQLServer.createEventHandler();
export const webSocketHandler = apolloService.graphQLServer.createWebSocketHandler();
```

Any help would be greatly appreciated as I'm stuck on why these errors could be occurring. Thank you for your time and effort!

**Comment by michalkvasnicak** [comment]
Do you export your lambda handlers? See https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L132

**Comment by minhazfm** [comment]
> Do you export your lambda handlers? See https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L132

Yes, I do already export the handlers, have added my handler code above just now

**Comment by michalkvasnicak** [comment]
It's really hard to say what's the problem. As you can see example is working so basically you'll need to go through and compare what are you doing differently.

Only thing that maybe can help you with troubleshooting is that maybe the request sent to WebSocket handler is malformed? Because it seems that it has a problem with https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/execute.ts#L182 because https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/execute.ts#L131 returns `null`.

**Comment by minhazfm** [comment]
I was able to log the earlier operation in that file (I'm using GraphQL playground to subscribe, and then Insomnia to send the mutation). Not sure if you notice anything off. I'll keep at it:

```
Operation -> {"variables":{},"extensions":{},"operationName":null,"query":"subscription {\n  stripeFeed {\n    message\n  }\n}\n","operationId":"1"}
```

So I was able to run the `chat-example-server` locally, but am confused how I could test it with just a GraphQL playground and Insomnia. Could you provide an example/steps to do that?

**Comment by minhazfm** [comment]
Thanks for your help @michalkvasnicak, I was able to figure out the multiple issues that were causing the webSocket connection to close out. Closing issue now. Thank you again for your hard work on this library!
