### ISSUE TITLE
AssertionError: "Please provide subscriptions to manage subscriptions"

### ISSUE THREAD

**Issue by louisholley** [michalkvasnicak/aws-lambda-graphql#125]
hello

i've just followed the tutorial and i'm getting the error below:

```
{
    "errorType": "AssertionError",
    "errorMessage": "Please provide subscriptions to manage subscriptions.",
    "code": "ERR_ASSERTION",
    "generatedMessage": false,
    "actual": false,
    "expected": true,
    "operator": "==",
    "stack": [
        "AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Please provide subscriptions to manage subscriptions.",
        "    at new DynamoDBConnectionManager (/var/task/webpack:/Users/louisholley/sanctuary/migrate.api-v2/node_modules/aws-lambda-graphql/dist/DynamoDBConnectionManager.js:120:1)",
        "    at Module.<anonymous> (/var/task/webpack:/Users/louisholley/sanctuary/migrate.api-v2/server.js:21:27)",
        "    at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1)",
        "    at /var/task/webpack:/webpack/bootstrap:83:1",
        "    at Object.<anonymous> (/var/task/server.js:87:10)",
        "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
        "    at Module.load (internal/modules/cjs/loader.js:985:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1025:19)"
    ]
}
```

my server.js file looks like this:

```
import {
  DynamoDBConnectionManager,
  DynamoDBEventProcessor,
  DynamoDBEventStore,
  DynamoDBSubscriptionManager,
  PubSub,
  Server,
} from "aws-lambda-graphql";

import { getUserFromHeaders } from "./helpers";

const eventStore = new DynamoDBEventStore();
const eventProcessor = new DynamoDBEventProcessor();
const subscriptionManager = new DynamoDBSubscriptionManager();
const connectionManager = new DynamoDBConnectionManager({
  subscriptionManager,
});
const pubSub = new PubSub({
  eventStore,
  // optional, if you don't want to store messages to your store as JSON
  // serializeEventPayload: false,
});

const server = new Server({
  connectionManager,
  eventProcessor,
  subscriptionManager,
  resolvers,
  typeDefs,
  context: async ({ event }) => {
    const user = await getUserFromHeaders(event.headers);
    return {
      pubSub,
      user,
    };
  },
});
```

any ideas?

**Comment by louisholley** [comment]
ok i just did `rm -rf node_modules` and then reinstalled and somehow it's working fine now? weird haha
